### ISSUE TITLE
Fix route generation for Rails 4.2 applications

### ISSUE THREAD

**Issue by nbibler** [codeschool/rapporteur#10]
Changes to Engines appears to have broken the route generation and recognition in Rails 4.2 applications. The engine's routes must now use `Rapporteur::Engine.routes.draw` and seemingly engine route names are not registered on the application parent (`main_app`).

**Comment by omghax** [comment]
I think the path forward is to require mounting of rapporteur. We could also auto-mount it, though that feels kinda hackish. Take a look at [qunit-rails](https://github.com/frodsan/qunit-rails/blob/master/config/routes.rb) for an example of auto-mounting.
