### ISSUE TITLE
Route is added as /status.json(.format) not /status(.format)

### ISSUE THREAD

**Issue by pbrisbin** [codeschool/rapporteur#9]
All I did was add the gem to the Gemfile (`~>3.1.0`) and bundle.

Console output (cleaned up a bit) showing the issue:

```
% rake routes | grep status.json
status GET    /status.json(.:format)  statuses#show {:format=>"json"}

% curl -D - 'localhost:5000/status.json'
HTTP/1.1 404 Not Found
...

% curl -D - 'localhost:5000/status.json.json'
HTTP/1.1 200 OK
...

{"revision":"...","time":"..."}
```

Rails version: 4.1.7.1

Thanks.

**Comment by nbibler** [comment]
I haven't seen that happen before. Strange. I'll take a look later today.

**Comment by nbibler** [comment]
While this gem doesn't officially support Rails 3.1, it _seems_ like it works fine just judging from the tests. In the meantime, I changed the way the route is generated to force the format and hopefully get Rails to not auto-append the optional `(.:format)` portion to the fixed route.

If you can, try to pull the latest `master` version into your app and see if you're still having the same troubles. I _think_ it's fixed. ;)

**Comment by pbrisbin** [comment]
> While this gem doesn't officially support Rails 3.1

You meant 4.1 here?

> If you can, try to pull the latest master version into your app and see if you're still having the same troubles

It looks better as far as `rake routes` goes (except format appears required now):

```
% rake routes | grep status
status GET  /status.:format statuses#show {:format=>"json"}
```

But it's still not working, and in fact `status.json.json` doesn't work now either.

```
% curl localhost:5000/status
% curl localhost:5000/status.json
% curl -H "Accept: application/json" localhost:5000/status.json
% curl -H "Accept: application/json" -H "Content-type: application/json" localhost:5000/status.json
```

All 404s.

**Comment by nbibler** [comment]
hah .. ack. Sorry .. misread your original post. It should certainly work in Rails 4.1.

**Comment by nbibler** [comment]
I would expect `/status.json.json` and `/status`,  to 404. I would not expect `/status.json` to 404. :confused:

**Comment by nbibler** [comment]
I'll try to create a new Rails 4.1 app tonight and test it ... if I find something wrong I'll get another fix together and let you know.

**Comment by pbrisbin** [comment]
Ideally, `/status` would work by having the route default to `:json` or when I pass the `Accept` header, but that'd be a feature request I guess.

**Comment by nbibler** [comment]
The intent was to pollute the routes as little as possible. So, strictly matching to `/status.json` seemed the least intrusive. You could always manually add a route to your application's route file to service `/status` if you'd like to with something like:

```ruby
get 'status', :to => 'statuses#show', :defaults => {:format => 'json'}

**Comment by pbrisbin** [comment]
That's fair. Doing that would probably also work around this bug. I can try it on Monday.

**Comment by nbibler** [comment]
Hmm.. that's fine. If there is a bug, I'd like to fix it. But if you'd like to work around it in the meantime, that's fine, too. :)

**Comment by nbibler** [comment]
I created a new Rails 4.1.9 app (with `rails new`):

```
$ bundle list | grep rails
  * rails (4.1.9)
```

### Current Rubygems release

Using the current production release of Rapporteur, I see the following routes:

```
$ bundle exec rake routes
Prefix Verb URI Pattern            Controller#Action
status GET  /status.json(.:format) statuses#show {:format=>"json"}
```

And I see the following curl responses:

```
$ curl -i http://localhost:3000/status.json | head -n1
HTTP/1.1 200 OK 

$ curl -i http://localhost:3000/status | head -n1
HTTP/1.1 404 Not Found 

$ curl -i http://localhost:3000/status.json.json | head -n1
HTTP/1.1 200 OK 

$ curl -i http://localhost:3000/status.json.xml | head -n1
HTTP/1.1 406 Not Acceptable 
```

Certainly, the `status.json.json` and `status.json.xml` responses are unexpected, as you've reported. The `status.json` endpoint appears to be responding as expected and the `status` does not respond, as expected.

### Current master

Updating to the current master (51a98c5c3ec058a89d73e12596667764210dd085) yields the following routes:

```
$ be rake routes
Prefix Verb URI Pattern     Controller#Action
status GET  /status.:format statuses#show {:format=>"json"}
```

And curl responses:

```
$ curl -i -s http://localhost:3000/status.json | head -n1
HTTP/1.1 200 OK 

$ curl -i -s http://localhost:3000/status.json.json | head -n1
HTTP/1.1 404 Not Found 

$ curl -i -s http://localhost:3000/status.json.xml | head -n1
HTTP/1.1 404 Not Found 

$ curl -i -s http://localhost:3000/status | head -n1
HTTP/1.1 404 Not Found
```

Which seems to be more correct than the current Rubygems release, so more than likely I'll package this up and release it soon.

Now, I know that you mentioned wanting `/status` to respond, but I'm still a bit hesitant to expand the routing footprint of the library when the most likely use case, in my mind, of the status endpoint is to  service automated systems (such as Pingdom). JSON formatting, I'm guessing, is not useful to present directly to users, so I hadn't really felt that having an extension-less or pretty URL was terribly meaningful.

Do you disagree?

**Comment by nbibler** [comment]
Pushed v3.2.0 to Rubygems this morning. Let me know if you're still seeing any issues.

**Comment by pbrisbin** [comment]
> Updating to the current master (51a98c5) yields the following routes

Yes, I see that too.

> And curl responses

Nope. I still get what I showed above. Specifically this one:

```
% curl -i -s http://localhost:5000/status.json | head -n1
HTTP/1.1 404 Not Found
```

If you're unable to reproduce in a clean Rails app of the same version, then it's most likely something specific to our routes or middleware stack causing an issue. If you want me to provide any more info to get to the bottom of it, feel free to ask. If you'd rather just consider it fixed that's fine with me.

> In my mind, of the status endpoint is to service automated systems (such as Pingdom). JSON formatting, I'm guessing, is not useful to present directly to users, so I hadn't really felt that having an extension-less or pretty URL was terribly meaningful

Seems perfectly reasonable and I have no problems with your approach or result. I can offer my own opinion/reasoning though, for whatever it's worth:

A format extension is exactly a human thing. It's a Windows-ism that has now become a Rails-ism. It's unnecessary. The endpoint should respond in the appropriate format based (only) on the `Accept` header. How the endpoint responds for `Accept: */*` is up to it, and we agree in this case JSON makes sense. "Pretty" URLs have nothing to do with it, it's just that `.json` is superfluous.

**Comment by nbibler** [comment]
Hmm.. Yeah. Those examples were a clean Rails 4.1 application with only a single gem dependency of Rapporteur.  So, I'm not sure how else I can go about debugging it for you if you're seeing something different.

I did notice that Rails 4.2 seems to have changed the Engine/Routing interface and Rapporteur appears to be broken in it... I made a [new ticket](https://github.com/codeschool/rapporteur/issues/10) for it.

I can see your point on responding to the `Accept` header. If the library responds to `/status` but is only configured to work with JSON responses, would you expect a `Not Found` or `Not Acceptable` response for all other cases (XML, HTML, etc.)? Or would you expect the library to attempt to accommodate XML and other system-specific format?  I guess at the end of the day I'm trying to gauge developer expectations with supporting a `/status` endpoint...

**Comment by pbrisbin** [comment]
That's a good question and shows the kind of confusion this `/status(.:format)` thing that Rails lets you do can cause: when you conflate representation and location, you have to think about `Not Acceptable` vs `Not Found` when it really shouldn't be a question.

Personally, I would want any of my routes to respond `Not Acceptable` if I can't provide the representation requested by the client. That's my understanding of the spec anyway. That said, once you can put a format in the URL, one could argue that `Not Found` makes sense too and things get murky. I like to avoid all that by not using URLs with formats in them.

It'd be great if the library also had XML/HTML representations to serve, but I don't need that feature myself.

**Comment by pbrisbin** [comment]
OK, I'm pretty sure the issue is that the project I'm on has a top-level `/:username` route that is not interacting correctly with the status route. It's probably trying to load a user named "status" with the JSON format. I'm not going to dig further and will just define my own route to your status page. Thanks very much for taking the time investigating this.

**Comment by nbibler** [comment]
No problem. Thanks for reporting it. :)

**Comment by tylerhunt** [comment]
Since this conversation touches on some of my reasons for #8, I'll go ahead and mention it here. If Rapporteur provided a mountable engine or Rack app, the solution to @pbrisbin's problem here would be to simply move the mount line in the routes file to a position higher than the `/:username` route. It would also do away with the `(.:format)` silliness. There's still the issue of breaking backwards compatibility to contend with, though. :confused:
